name: CI

on:
    push:

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v3
            - name: Installing Rust toolchain
              run: rustup toolchain install stable
            - uses: Swatinem/rust-cache@v2
            - name: Checking formatting
              run: cargo fmt --check
            - name: Checking lints with all features
              run: cargo clippy --all-targets --all-features -- -D warnings
            - name: Checking doc references
              uses: Icelk/rustdoc-link-check@v2
              with:
                  private: true
            - name: Testing project
              run: cargo test

    build:
        needs: [check]
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v1
            - name: Installing Rust toolchain
              run: rustup toolchain install stable --profile minimal
            - uses: Swatinem/rust-cache@v2
            - name: Compiling
              run: cargo rustc --profile production
            - name: Upload bin artefact
              uses: actions/upload-artifact@v3
              with:
                  name: strange-attractor-renderer
                  path: target/production/strange-attractor-renderer
